name = "svelte-kit-demo"
account_id = "32a8245cd45a24083dd0acae1d482048"
route = "cloudflare-workers-demo.svelte.dev/*"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = true

